pipeline{
  agent any
       stages{
       stage("Git Checkout"){
           Steps{
                      git credentialsId: 'github',
                     }
                  }
            stage("Maven Build"){
              Steps{
                          sh "mvn clean install"
                       }
                   }
            stage("Building image"){
                         Steps{ 
         sh "docker build -t  cmr-repo/myapp:1.0"
         sh "docker run -dt cmr-repo/myapp:1.0"
sh "docker tag cmr-repo/myapp:1.0
sh "docker push
                    }
                }
           }
       }
