pipeline{
  agent any
       stages{
       stage("Git Checkout"){
           Steps{
                      git credentialsId: 'github',url: 'https://github.com/Ashok91825/practice.git'
                     }
                  }
            stage("Maven Build"){
              Steps{
                          sh "mvn clean install"
                       }
                   }
            stage("Building image"){
                         Steps{ 
                            sh "docker build -t  cmr-repo/myapp:1.0"
                            sh "docker run -dt cmr-repo/myapp:1.0"
                            sh "docker tag cmr-repo/myapp:1.0 ashok9182/cmr-repo"
                            sh "docker push docker pull ashok9182/cmr-repo"
                        } 
                     }
                  }
               }
